# -*- coding: utf-8 -*-
"""Seaborn_Library.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-nHCXY7vkDIwZvD6mg6A5blW332MraMD
"""

#Seaborn

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df = sns.load_dataset('tips')

df.head(3)

df.tail(10)

hue_colors = {"No":"red", "Yes":"green"}

sns.scatterplot(x="total_bill" , y="tip",
                hue = "smoker", hue_order = ["No","Yes"],
                palette = hue_colors,
                data = df)
plt.show()

sns.countplot(x="sex",
                hue = "smoker",
                data = df)
plt.show()

hue_colors = {"No":"red", "Yes":"green"}

sns.relplot(x="total_bill" , y="tip",
                hue = "smoker", hue_order = ["No","Yes"],
                palette = hue_colors,
                data = df)
plt.show()

sns.relplot(x = "total_bill" , y = "tip", data = df,
           kind = "line",hue = "day", style = "day", markers = True, dashes = False)
plt.show()

sns.catplot(x = "smoker" ,
            data = df, kind = "count")
plt.show()

"""#Plotly"""

import plotly.express as px

px.data.gapminder

df = px.data.gapminder()

df.head(10)

barplot = px.bar(df,x = "continent", y = "lifeExp", color = "continent",
                 text = "continent",
                 title = "SAMPLE PLOTLY GRAPH BY NANA",
                 labels = {"continent":"CONTINENT", "lifeExp":"LIFE EXPECTANCY"},
                 hover_data = ["pop", "gdpPercap","iso_num","country","continent"])

barplot.show()



"""#Bokeh"""

import bokeh as bk

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df = sns.load_dataset('tips')

df.head(10)

df["total_bill"].median()

df["total_bill"].mode()

df["total_bill"].mean()